# Generated by Django 4.2.11 on 2024-03-13 19:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(choices=[('Table 1 (2 seats)', 'Table 1 (2 seats)'), ('Table 2 (2 seats)', 'Table 2 (2 seats)'), ('Table 3 (2 seats)', 'Table 3 (2 seats)'), ('Table 4 (4 seats)', 'Table 4 (4 seats)'), ('Table 5 (4 seats)', 'Table 5 (4 seats)'), ('Table 6 (4 seats)', 'Table 6 (4 seats)'), ('Table 7 (8 seats)', 'Table 7 (8 seats)'), ('Table 8 (8 seats)', 'Table 8 (8 seats)')], default='Table 1 (2 seats)', max_length=50)),
                ('day', models.DateField(default=datetime.datetime.now)),
                ('time', models.CharField(choices=[('1 PM', '1 PM'), ('3 PM', '3 PM'), ('5 PM', '5 PM'), ('7 PM', '7 PM'), ('9 PM', '9 PM')], default='1 PM', max_length=5)),
                ('time_ordered', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
