# Generated by Django 4.2.11 on 2024-03-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_table_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_booking',
            name='special_requirements',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
