# Generated by Django 4.2.11 on 2024-03-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_table_booking_special_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_booking',
            name='special_requirements',
            field=models.TextField(blank=True, default='No requirements.', max_length=2000, null=True),
        ),
    ]
